// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://jcxhagmfbezpgrxdxfvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_FYAA7exANWNkEdAqkTSX7Q_y7wHeWOe";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Untyped client — the connected database schema diverges from the generated types
// in many places after the project remix. We rely on runtime checks instead of compile-time types.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
